Makefile

Hey! This small PR fixes ocicl installation under Wine with MiGW — it looks like its cp.exe does not like the semicolon very much:
```
cp ocicl.exe /ucrt64/bin ;
cp: can't create ';/ocicl.exe': No such file or directory
cp: omitting directory '/ucrt64/bin'
```
Withoit the semicolon it works fine.

Fix installation under Wine + MinGW

---

Makefile

Multi-line shell commands in make targets need some special escaping.
`make install` runs without error and extracts the correct tarball. 
Fixes: #19

Fix macOS installation

---

.github/workflows/macos.yml

First time working with GH actions and I'm not super confident about it, but it seems to do its job. This is basically a copy of the `linux.yml` with adjusted URLs and PATHs.
Currently x86_64/AMD64 only. See the [GH Roadmap](https://github.com/github/roadmap/issues/528). ARM64 support is planned for Q3 2023.

Add macOS CI workflow

---

ocicl.lisp

Hi,
I'd like to build an in-house OCI registry for in-house libraries. For this to work I extended `ocicl` to handle multiple configured registries in `~/.local/share/ocicl/ocicl-registry.cfg`. 
Let me know if you think this would be a feature for everybody to benefit from. 
Best,
Sebastian

Multiple registries

---

ocicl.lisp

Addition of `:verbose t` to `asdf:load-system` is respected. This way it doesn't look like the implementation has hung when downloading packages.

feat(ocicl): Respect ASDF verbose in system-definition-searcher

---

runtime/ocicl-runtime.lisp

feat(ocicl-runtime): Respect ASDF verbose in system-def-searcher

---

ocicl.lisp

UIOP:READ-FILE-STRING returns all content and a trailing newline, making the following calling to UIOP:CHDIR to fail. Changing this to UIOP:READ-FILE-LINE as it doesn't make much sense to allow multiple lines in the file anyway.

fix: correctly read ocicl-globaldir.cfg

---

README.md
runtime/ocicl-runtime.lisp

This should make it easier to use ocicl in a global-only manner.
Please change the `*global-only*` to another name if that's more taste-appropriate.
PS: My current pet-peeve is that ocicl tries to create a `systems.csv` and the `systems` directory in every damn directory I start the lisp process in. This PR resolves this issue.

Add a *global-only* parameter to the runtime

---

setup.lisp

Hi @atgreen ,
I was a little absent and had to start from scratch building `ocicl` and stumbled over a problem an thought I may improve it. 
Just two little changes. 
1. Use `uiop:ensure-directory-pathname` on `OCICL_PREFIX` to ensure we're working with a directory path (😅) when creating sub-directories. 
Without the trailing slash, the `bin` directory is added before the last path segment:
```lisp
CL-USER> (merge-pathnames (make-pathname :directory '(:relative "bin")) 
"/home/foo/software/ocicl-2.3.9")
#P"/home/foo/software/bin/ocicl-2.3.9"
^^^
```
2. Use `uiop:getenvp` because it returns `nil` when the env variable is empty, as well.

Ensure OCICL_PREFIX env variable is a directory

---

ocicl.lisp

I had multiple registries configured in `ocicl-registry.cfg` which were discarded after `setup` ran again while building a new executable. 
I think that, once the configuration was created, `ocicl` shouldn't touch it again and overwrite any existing configuration with default values.
What do you think @atgreen?

Don't overwrite config if present

---

README.md
runtime/ocicl-runtime.lisp

1. Check if `(require 'asdf)` already satisfies ASDF version requirement. I decided to use 3.3.5 because mentioned [here](https://github.com/ocicl/ocicl/issues/67#issuecomment-2294900303)
2. Compile the bundle `asdf.lisp` and cache the fasl file based on implementation and machine type. Loading the fasl file is faster than loading the lisp file. 
3. Muffle annoying redefinition warnings when loading bundled ASDF.

Compile bundled ASDF and muffle redefinition warnings

---

runtime/ocicl-runtime.lisp

add 3 new functions
- `check-if-program-exists`: check if a program exists and is executable by directly invoking the program and checking the result code
- `warn-if-program-doesnt-exist`: added to keep consistency between warning messages
- `warn-if-missing-required-programs`: used as a one stop shop for warning before required programs are ran (e.g install and version check)
Fixes #69

feat: warn users (if *verbose*) that certain programs don't exist

---

oras/README.md

The link in oras/README.md has been broken by the oras.land site; this PR links to the page's new address.

Fix broken link in oras/README.md

---

README.md
runtime/ocicl-runtime.lisp

I found it bothersome that `*verbose*` literally translated to `t` when invoking `FORMAT`. I should be in control of where ocicl logs to, and in some cases, I want `*error-output*` or my own file.
- Add `SHOULD-LOG` which checks if *verbose* is non-nil and a valid
output stream.
- Replace direct `t` `FORMATS` with `*verbose*`, if `SHOULD-LOG` permit.

feat: enhance *verbose* to allow for different output streams

---

ocicl.lisp

This is an attempt at fixing #89 to restore the behavior described in the README:
> Now try deleting the systems directory, and loading str again as above. ocicl will download the exact version specified in the systems.csv file.

Download system when asd file is not present

---

ocicl.lisp

Instead of manual chdir with unwind-protect.
This feels a bit cleaner, and uiop:with-current-directory does unwind-protect with chdir anyway

Use uiop:with-current-directory in main

---

ocicl.lisp

Implements #90, examples using this repository:
- Adds helper functions `unmangle` and `system-group`
- `ocicl remove` removes top level systems unconditionally. Prints "full names" removed. Example:
``` sh
$ grep cl+ssl systems.csv
cl_plus_ssl.test, ghcr.io/ocicl/cl_plus_ssl@sha256:acb61e8...
cl_plus_ssl, ghcr.io/ocicl/cl_plus_ssl@sha256:acb61e8...
$ ocicl remove cl+ssl
; removed cl_plus_ssl@sha256:acb61e8e4d3efcb23f4d86405ad22fdca2d685268c664735c962646a09706ab6
$ grep cl+ssl systems.csv
```
- `ocicl autoremove` removes systems only if they are known not to be depended on by other systems in systems.csv. Example:
```sh
$ ocicl autoremove usocket
; not removing systems (usocket-server usocket-test usocket), depended on by one of: (cl+ssl cl+ssl.test)
$ ocicl autoremove tar
; removed …
```

Implement ocicl remove, minor fix to download-system

---

ocicl.lisp

When a system was present in systems.csv, but did not exist in the systems directory, ocicl's system searcher would not attempt to download the file.
Fixes #109

Fix ocicl install sometimes not installing dependencies

---

ocicl.lisp

Previously we only built the top level dependency list based on systems registered in ocicl.csv, which did not fully consider e.g. slash systems in dependency resolution.
Additionally, the dependency tree traversal was incomplete.

Do more complete dependency resolution in ocicl remove

---

README.md
ocicl.lisp

Cleans system directories not listed in ocicl.csv
Currently this just goes and does it. Do we want:
- To ask for confirmation?
- A `--dry-run` option to show what would be deleted?

Implement ocicl clean

---

README.md
ocicl.asd
ocicl.lisp
tree.lisp

- Adds fairly simple but extensible generic tree printer (supports ascii and unicode tree printing) in `tree.lisp`
- Prints installed systems in tree view
- Defaults to top systems in ocicl.csv, and depth = 1 (a flat list essentially)
- Allows specifying top systems to show
- Can specify --depth=n or --depth=max to show full tree
- Omits sub-trees for seen systems with indicator (but prints the seen system itself). This avoids ginormous trees and repetition of information.
- ❓ The  tree defaults to unicode right now, but maybe we should look at LANG to decide?
Uses extra characters and/or colors for more info:
- green means showing new system, dim means system was already printed (you lose this visual info in no-color mode, but I think that's okay since we're not re-printing the deps …

New command: ocicl tree

---

ocicl.asd
ocicl.lisp

As a first step to addressing #58, I made an attempt to increase the portability of the ocicl functionality by replacing all of the sbcl dependent code
Certain dependencies (such as bordeax threads) still aren't entirely portable across all implementations (in particular, CLISP), so future work might need to be done there if portability is an important requirement. 
Likely next steps:
- reduce the size of ocicl dependencies in order to make it easier to ship ocicl as a single file (ie, using monolithic-concatenate-source-op like asdf)
- merge `ocicl.lisp` and `runtime/ocicl-runtime.lisp` into one file, removing the need for a binary to be installed.
I also fixed several compilation warnings and notes I came across while building

Portability improvements

---

ocicl.lisp

Adds colors to more ocicl commands (list, libyear, install, remove)
Eventually, it'd be nice to have a nicer paradigm (e.g. a custom format function) to optionally add colors, but I'm not sure what the best interface for this is, and existing packages that do this (e.g. cl-ansi-term) seemed to pull more deps than necessary. 
I can provide screenshots if wanted. I also changed a couple messages to make them more consistent/clearer (e.g. download**ed** vs download**ing**)

More colors
